name: BUILD-IMAGEN-DOCKER

on:
  push:
    branches: ["develop"]
env:
   versionbase: latest
   reponamedocker: arch-plat-devops-image
jobs:
  BUILD-IMAGE:
    runs-on: [self-hosted, x64, Windows, devops01]

    steps:
      - uses: actions/checkout@v4.1.1
     
      - name: Autenticacion docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: construcion de la imagen Docker
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
             ${{env.reponamedocker}}/imagesjk:${{github.run_number}}
