name: BUILDIMAGE

on:
  push:
    branches:
      - 'develop'
env:
    nombredeimagen: dockerio
    version: latest 
jobs:
  BUILDIMAGE:
    runs-on:  [self-hosted, x64, Linux, images]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        dockerfile: Dockerfilejk
        context: ./src
       
    - name: Build Docker image 
      run: |
        docker build -t ${{env.nombredeimagen}}:${{env.version}} ./src
