name: CI-CD

on:
  push:
    branches: ["main"]
env:
   versionbase: latest
   
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
     
      - name: Autenticacion docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: contrucion de la imagen Docker
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
             ${{ secrets.DOCKER_USERNAME }}/gitAction-news:${{github.run_number}}
                         
          

    
    
