name: CI-CD

on:
  push:
    branches: ["main"]
env:
   versionbase: latest
   reponamedocker: brixtondevops
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
     
      - name: Autenticacion docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: contrucion de la imagen Docker
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
             ${{env.reponamedocker}}/action-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Definiendo el contexto
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG}}
      - name: Deploy apps a Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images:  ${{env.reponamedocker}}/action-news:${{github.run_number}}           
          manifests:
            K8S/deployment.yaml

    
    
